### ISSUE TITLE
latest react@0.14.1

### ISSUE THREAD

**Issue by lowsky** [alexlande/react-style-guide#10]
Please support latest react version: 0.14.1 
Currently, we are stuck with react-style-guide at 0.13

npm install react-style-guide
Error:
Peer react-style-guide@1.1.6 wants react@>=0.12.0 <0.14.0

**Comment by lowsky** [comment]
Currently, builds fail caused by this error:
./~/highlight.js/lib/languages/autoit.js
Module build failed: RangeError: Maximum call stack size exceeded
Even on node v4.1.0 (and npm v2.14.3)
and also after upgrading to latest highlight.js@8.9.1

**Comment by alexlande** [comment]
Fixed :metal:

**Comment by lowsky** [comment]
... and thanks, it works fine!
