### ISSUE TITLE
When using React Element as prop: Uncaught TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by AndrewRayCode** [alexlande/react-style-guide#3]
If you have a React element as a prop of a component in the style guide, the page will fail to load with

```
Uncaught TypeError: Converting circular structure to JSON
```

This is reproducible by running `webpack --watch`, modify `example/app.jsx` to use the code:

```
<CoolButton title={<div>title</div>} type="primary">
```

Then when webpack rebuilds, `mv ./app.js examples/app.js` and reload the page. The error blocks the page load.

**Comment by AndrewRayCode** [comment]
Still researching this one, I thought it was from the `highlightMarkup` but as far as I can tell it's not even getting in there, simply adding a prop makes the app crash without debugger statements being hit.

**Comment by AndrewRayCode** [comment]
It's from https://www.npmjs.com/package/react-to-jsx

**Comment by AndrewRayCode** [comment]
See above ticket.

**Comment by AndrewRayCode** [comment]
Reopening to use as placeholder ticket to bump `react-to-jsx` after the issue is resolved

**Comment by alexlande** [comment]
Forgot to close this when it was fixed in `react-to-jsx`. Time for an issue closing pick-me-up!
