### ISSUE TITLE
Component description (HTML ? Code highlight ?)

### ISSUE THREAD

**Issue by rafaelchiti** [alexlande/react-style-guide#6]
Hey, thanks for contributing this library pretty nice!.
We built a component library at my current client and now we are trying to find a standarize way of documenting the component but also of showing that docs in the style guide as part of the description.
Wondering if we could integrate something here with the library like a way of setting the description to understand some type of doc or html and show it in the style guide.
An idea that came up recently was to write the documentation of our shared components as a template literal so we do something like:

```
export let docs = `
  Docs here
`

expor default Component extend React.Component {
}

Component.docs = docs;
```

Any thoughts?

**Comment by alexlande** [comment]
Hey @rafaelchiti, thanks for checking it out!

That sounds like a good plan to me, and you should be able to do it right now, unless I'm misunderstanding. You can pass the docs into the `description` prop: https://github.com/alexlande/react-style-guide#description.

If you want more formatting than a plain string, you can add `descriptionIsHtml` and convert the docs to HTML however you'd like beforehand. (With marked, for example https://www.npmjs.com/package/marked).
